language: node_js
node_js:
- 8.11.3
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
- export PATH="$HOME/.yarn/bin:$PATH"

script:
- yarn test

deploy:
  provider: heroku
  api_key:
    secure: OX8hMli/p6z9jyzwZBMolBwdlciTb46ewowwSjmpKiUQwMBz/5FZhvSMqQpabW3+8bJ2BB+FlK5kR2Qy4XHaRLyhm/wh9HltuRRbOPtIrF/RvrYU9iVvpafPzPM714oW2nFNfTILpkEvp4unNbKds3P0TyzluFyYgBYqmIj5Dc/0BImyDrNQlEmAxzxPXS0kHtMcezfVZu0bPChbRCsVLdRTXgGURoxp7sAH6vItaYCcjvUznOoUkCJCwKssLe0MVzRPkVJu87ebFBw+e/IO2Uy9MEh4P095pTOclzlaQ4nQGhD/VCyh0Y/pQFlFUYgMTvwYhdplvY/dQRsYVVcJlq+meucvtN/JipKnwXhL0uxuImXFSvNGDakJUX4LMtVrizI/+wdifJ3KrTKsan2gn7hybs3ht+jAEKCWfOE7f419VgEp7gU3tVTrut5/58mPNL0jmb5DEJJlUgbNdD3BPgTxMSxQ+WyqVhxLMOqFVs4tdgTwAD9xgTJLBfutrza6wtHW4bELzTdRqn+VRRz1I+pQF7Ucpo+EXmxeUWKjXcKbIIPxmxp+i/7xehsgBk+YztN+U5DaESM/xvQn3Sfu5c+mPam+gT5/1PnFdTUMInGl56P1QmKvNjPuMyhuv7nSSXm4BT6J8hwsAZQ5hY0jn1chsSNnm3dmtJAgN8Uk11c=
  app: learn-travisci
